### ISSUE TITLE
chosen option not matching the correct action

### ISSUE THREAD

**Issue by j3ang** [zackfrank/millionaire#1]
![image](https://user-images.githubusercontent.com/16583879/42614528-ecea0930-856b-11e8-8cd8-70091fc01a06.png)

**Comment by zackfrank** [comment]
fixed! see latest commit :)

**Comment by zackfrank** [comment]
<img width="974" alt="fixed issue" src="https://user-images.githubusercontent.com/36717440/42618565-0291eab4-857b-11e8-8e02-ecc9a79a601d.png">
